import os

PLAID_CLIENT_ID = os.getenv('REACT_APP_PLAID_CLIENT_ID')
PLAID_SECRET = os.getenv('REACT_APP_PLAID_SECRET')
PLAID_PUBLIC_KEY = os.getenv('REACT_APP_PLAID_PUBLIC_KEY')
PLAID_ENV = os.getenv('REACT_APP_PLAID_ENV')