# Generated by Django 2.1 on 2018-08-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
